name: A-core workflow

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      version-type:
        required: true
        type: string
    secrets:
      token:
        required: false

jobs:
  linter:
    if:  github.event_name != 'workflow_dispatch' || github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: linter
      run: |
        echo "linter job"

  build-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: build app
      run: |
        echo "build job"

  containerfile-scan:
    if:  github.event_name != 'workflow_dispatch' || github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: containerfile-scan
      run: |
        echo "containerfile-scan job"

  image-scan:
    if:  github.event_name != 'workflow_dispatch' || github.ref_name == 'main'
    needs: [build-app, containerfile-scan]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: containerfile-scan
      run: |
        echo "containerfile-scan job"

  test:
    if:  github.event_name != 'workflow_dispatch' || github.ref_name == 'main'
    needs: [build-app]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: containerfile-scan
      run: |
        echo "containerfile-scan job"

  push-test:
    if: |
      (github.event_name == 'pull_request' && github.base_ref == 'main') ||
      (github.event_name == 'workflow_dispatch' && github.ref_name != 'main')
    needs: [build-app]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: containerfile-scan
      run: |
        echo "containerfile-scan job"

  check-pr-level:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: containerfile-scan
      run: |
        echo "containerfile-scan job"

  determine-version:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: containerfile-scan
      run: |
        echo "containerfile-scan job"

  determine-version-dispatch:
    if: github.event_name == 'workflow_dispatch' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: containerfile-scan
      run: |
        echo "containerfile-scan job"
        
  push-prod:
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
    needs: [linter, build-app, containerfile-scan, image-scan, test, determine-version-dispatch]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: containerfile-scan
      run: |
        echo "containerfile-scan job"

  bump-version :
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
    needs: [push-prod]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: containerfile-scan
      run: |
        echo "containerfile-scan job"


        



        
        
